### ISSUE TITLE
Nice job

### ISSUE THREAD

**Issue by cyisfor** [Overv/Open.GL#46]
I have a serious issue with this tutorial. It's the singlemost best tutorial on OpenGL I've ever seen, old glBegin() style and new VBO style combined. There is a distinct lack of all my money, because I keep shoving it at the screen and nothing happens. Shame on you for making things so clear and sensible and giving me something pleasant to read this afternoon. At least you use C++, or else I would have to admonish you for having no flaws whatsoever.

**Comment by Overv** [comment]
Finally some genuine feedback! I'm glad you brought up these points, because there is another branch I'm currently working on that deals with these deficiencies.

I think that you'll be pleased to learn that C++ is actually an excellent choice for building this kind of technology. It introduces undefined behaviour into the website to create an instability in the space-time continuum that allows for transporting the user's money to me.

**Comment by cyisfor** [comment]
WOAH HEY WHERE DID ALL MY MONEY GO
