### ISSUE TITLE
Stencil buffer with SDL2

### ISSUE THREAD

**Issue by AngeloG** [Overv/Open.GL#53]
For SDL2, it is required to add this line to get a stencil buffer of 8 bits:

    SDL_GL_SetAttribute(SDL_GL_STENCIL_SIZE, 8);

If you don't call this, there will be no stencil buffer. This isn't mentioned anywhere, so will go by unnoticed in the later page making the reflection of the cube. Perhaps this is worth putting somewhere in the "Context Creation" page?

**Comment by Overv** [comment]
Thanks for spotting that. I've added clarification to the SDL section in the context creation chapter.

**Comment by sechshelme** [comment]
It would be beneficial if this were also mentioned here.
I tried for several hours before I found out that you still have to specify the stencil buffer in the context creation.
Since I use Pascal and therefore don't use glew for context creation, this was really difficult.
That's why I missed the following line.
`settings.stencilBits = 8;`

https://open.gl/depthstencils
